from typing import Protocol

from apps.models import App, RegistrationRequest


class RegistrationRequestStorageBackend(Protocol):
    async def get_by_id(self, request_id: str) -> RegistrationRequest | None: ...

    async def list_all(self) -> list[RegistrationRequest]: ...

    async def save(self, request: RegistrationRequest) -> None: ...

    async def close(self) -> None: ...


class AppStorageBackend(Protocol):
    async def get_by_id(self, app_id: str) -> App | None: ...

    async def list_all(self) -> list[App]: ...

    async def save(self, app: App) -> None: ...

    async def close(self) -> None: ...


__all__ = ["AppStorageBackend", "RegistrationRequestStorageBackend"]
