from typing import Protocol

from assets.storage.models import AssetInDB


class AssetsStorageBackend(Protocol):
    async def get_by_id(self, asset_id: str) -> AssetInDB | None: ...
    async def list_all(self) -> list[AssetInDB]: ...
    async def list_by_parent(self, parent_id: str | None) -> list[AssetInDB]: ...
    async def save(self, asset: AssetInDB) -> None: ...
    async def delete(self, asset_id: str) -> None: ...
    async def get_children(self, asset_id: str) -> list[AssetInDB]:
        """Return only the direct children of *asset_id*."""
        ...

    async def get_descendants(self, asset_id: str) -> list[AssetInDB]:
        """Return every node in the subtree below *asset_id*.

        Recursive, excludes *asset_id* itself.
        """
        ...

    async def update_descendant_paths(self, asset_id: str) -> None: ...

    async def get_next_position(self, parent_id: str) -> int:
        """Return the next available position for a new child of *parent_id*."""
        ...

    async def reorder_siblings(self, parent_id: str, ordered_ids: list[str]) -> None:
        """Set position values for the given sibling IDs in order (0, 1, 2, ...)."""
        ...

    async def close(self) -> None: ...
