from typing import Protocol

from device_views.models import DeviceView


class ViewStorage(Protocol):
    async def list(self) -> list[DeviceView]: ...
    async def get(self, view_id: str) -> DeviceView: ...
    async def create(self, view: DeviceView) -> DeviceView: ...
    async def update(self, view: DeviceView) -> DeviceView: ...
    async def delete(self, view_id: str) -> None: ...
    async def close(self) -> None: ...
