import type { FC } from "react";
import {
  Activity,
  AirVent,
  BatteryCharging,
  BellRing,
  Building2,
  Camera,
  Car,
  ChartColumn,
  ChartLine,
  CircleGauge,
  CloudRain,
  CloudSun,
  Cpu,
  DoorOpen,
  Droplet,
  DropletOff,
  Droplets,
  Factory,
  Fan,
  Flame,
  Gauge,
  Heater,
  House,
  KeyRound,
  Layers,
  Leaf,
  Lightbulb,
  Lock,
  MapPin,
  ParkingCircle,
  PieChart,
  Plug,
  PlugZap,
  Power,
  Radio,
  Server,
  Settings,
  ShieldAlert,
  ShowerHead,
  Siren,
  Snowflake,
  Sun,
  SunDim,
  Thermometer,
  ThermometerSnowflake,
  ThermometerSun,
  Trees,
  TriangleAlert,
  UtilityPole,
  Warehouse,
  Waves,
  Wifi,
  Wind,
  Wrench,
  Zap,
  Bath,
} from "lucide-react";
import type { DashboardIcon } from "@gridone/sdk";
import type { IconComponent } from "@/components/forms/IconGrid";

/** One drawing per key of the API's icon vocabulary. `satisfies` keeps the
 *  two in step: a key the API adds fails the type check here until drawn,
 *  and a drawing the API no longer names is refused. */
export const DASHBOARD_ICONS = {
  thermometer: Thermometer,
  "thermometer-sun": ThermometerSun,
  "thermometer-snowflake": ThermometerSnowflake,
  snowflake: Snowflake,
  flame: Flame,
  heater: Heater,
  sun: Sun,
  "sun-dim": SunDim,
  droplet: Droplet,
  droplets: Droplets,
  "droplet-off": DropletOff,
  waves: Waves,
  bath: Bath,
  "shower-head": ShowerHead,
  wind: Wind,
  fan: Fan,
  "air-vent": AirVent,
  gauge: Gauge,
  "circle-gauge": CircleGauge,
  zap: Zap,
  plug: Plug,
  "plug-zap": PlugZap,
  "utility-pole": UtilityPole,
  "battery-charging": BatteryCharging,
  lightbulb: Lightbulb,
  power: Power,
  activity: Activity,
  "chart-line": ChartLine,
  "chart-column": ChartColumn,
  "pie-chart": PieChart,
  cpu: Cpu,
  server: Server,
  radio: Radio,
  wifi: Wifi,
  siren: Siren,
  "bell-ring": BellRing,
  "shield-alert": ShieldAlert,
  "triangle-alert": TriangleAlert,
  "door-open": DoorOpen,
  lock: Lock,
  "key-round": KeyRound,
  camera: Camera,
  car: Car,
  "parking-circle": ParkingCircle,
  house: House,
  "building-2": Building2,
  warehouse: Warehouse,
  factory: Factory,
  leaf: Leaf,
  trees: Trees,
  "cloud-sun": CloudSun,
  "cloud-rain": CloudRain,
  layers: Layers,
  "map-pin": MapPin,
  wrench: Wrench,
  settings: Settings,
} as const satisfies Record<DashboardIcon, IconComponent>;

export const DASHBOARD_ICON_KEYS = Object.keys(DASHBOARD_ICONS) as [
  DashboardIcon,
  ...DashboardIcon[],
];

/** The dashboard's icon, or nothing: an entry without one shows no glyph. */
export const DashboardIconGlyph: FC<{
  icon: DashboardIcon | null | undefined;
  className?: string;
}> = ({ icon, className }) => {
  if (!icon) return null;
  const Icon = DASHBOARD_ICONS[icon];
  return <Icon aria-hidden className={className} />;
};
