name: Bump Version

on:
  push:
    branches:
      - main

jobs:
  bump:
    name: Bump version & changelog
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create bump and changelog
        id: cz
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.BUMP_TOKEN }}
          changelog_increment_filename: body.md
          extra_requirements: uv
          no_raise: 21

      - name: Trigger release workflow
        if: steps.cz.outputs.version != ''
        env:
          GH_TOKEN: ${{ secrets.BUMP_TOKEN }}
        run: |
          gh workflow run release.yml --field tag="v${{ steps.cz.outputs.version }}"
